#!/usr/bin/env python3
import argparse
from pathlib import Path


def resource_kind(path: Path) -> str:
    suffix = path.suffix.lower()
    if suffix == ".css":
        return "jellyframe::HostResourceKind::Stylesheet"
    if suffix == ".js":
        return "jellyframe::HostResourceKind::ClassicScript"
    if suffix in {".png", ".jpg", ".jpeg", ".gif", ".webp", ".bmp"}:
        return "jellyframe::HostResourceKind::Image"
    if suffix in {".bdf", ".fnt", ".jffont", ".ttf", ".otf", ".woff", ".woff2"}:
        return "jellyframe::HostResourceKind::Font"
    return "jellyframe::HostResourceKind::Other"


def cpp_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def emit_byte_array(name: str, data: bytes) -> str:
    lines = [f"constexpr std::uint8_t {name}[] = {{"]
    for offset in range(0, len(data), 16):
        chunk = data[offset:offset + 16]
        values = ", ".join(f"0x{byte:02x}" for byte in chunk)
        lines.append(f"    {values},")
    lines.append("};")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate a JellyFrame ESP32-S3 resource bundle.")
    parser.add_argument("--root", required=True, help="Resource root directory.")
    parser.add_argument("--url-prefix", default="/app", help="URL prefix for generated resources.")
    parser.add_argument("--output", required=True, help="Generated C++ source path.")
    args = parser.parse_args()

    root = Path(args.root).resolve()
    output = Path(args.output).resolve()
    url_prefix = "/" + args.url_prefix.strip("/")
    files = sorted(path for path in root.rglob("*") if path.is_file())

    output.parent.mkdir(parents=True, exist_ok=True)
    with output.open("w", encoding="utf-8", newline="\n") as generated:
        generated.write("// Generated by ports/esp32s3-idf/tools/generate_resource_bundle.py.\n")
        generated.write("// Do not edit by hand.\n\n")
        generated.write('#include "jellyframe_esp32s3_resources.h"\n\n')
        generated.write("#include <cstdint>\n\n")
        generated.write("namespace jellyframe_esp32s3 {\n")
        generated.write("namespace {\n\n")

        entries = []
        for index, path in enumerate(files):
            relative = path.relative_to(root).as_posix()
            url = f"{url_prefix}/{relative}"
            symbol = f"kResource{index}"
            data = path.read_bytes()
            generated.write(emit_byte_array(symbol, data))
            generated.write("\n\n")
            entries.append((url, resource_kind(path), symbol, len(data)))

        generated.write("constexpr ResourceEntry kGeneratedEntries[] = {\n")
        for url, kind, symbol, size in entries:
            generated.write("    ResourceEntry{\n")
            generated.write(f"        {cpp_string(url)},\n")
            generated.write(f"        {kind},\n")
            generated.write(f"        {symbol},\n")
            generated.write(f"        {size},\n")
            generated.write("    },\n")
        generated.write("};\n\n")
        generated.write("} // namespace\n\n")
        generated.write("const ResourceBundle& generated_resource_bundle() {\n")
        generated.write("    static constexpr ResourceBundle bundle{kGeneratedEntries, ")
        generated.write(f"{len(entries)}")
        generated.write("};\n")
        generated.write("    return bundle;\n")
        generated.write("}\n\n")
        generated.write("} // namespace jellyframe_esp32s3\n")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
