"""Generate palette CSS, SVG and reference from palette.json (Python stdlib only)."""
import json
import re
from html import escape
from pathlib import Path

ROOT = Path(__file__).resolve().parent
data = json.loads((ROOT / 'palette.json').read_text(encoding='utf-8'))


def kebab(value):
    return re.sub(r'([A-Z])', r'-\1', value).lower()


def luminance(value):
    rgb = [int(value[i:i + 2], 16) / 255 for i in (1, 3, 5)]
    linear = [v / 12.92 if v <= .04045 else ((v + .055) / 1.055) ** 2.4 for v in rgb]
    return sum(v * weight for v, weight in zip(linear, (.2126, .7152, .0722)))


def contrast(a, b):
    lo, hi = sorted((luminance(a), luminance(b)))
    return (hi + .05) / (lo + .05)


css = ['/* Generated by generate_palette.py. Edit palette.json, then regenerate. */', ':root {']
for group in ('brand', 'logo', 'accent', 'neutral', 'material'):
    for name, value in data[group].items():
        css.append(f'  --jf-{group}-{kebab(name)}: {value};')
css.append('}')
for theme, selector in [('light', ':root, .jf-theme-light'), ('dark', '.jf-theme-dark')]:
    css.append(f'\n{selector} {{')
    for name, value in data['themes'][theme].items():
        css.append(f'  --jf-color-{kebab(name)}: {value};')
    css.append('}')
(ROOT / 'palette.css').write_text('\n'.join(css) + '\n', encoding='utf-8')

checks = []
for theme, colors in data['themes'].items():
    pairs = [('text', 'background'), ('text', 'surface'), ('text', 'surfaceRaised'),
             ('textMuted', 'background'), ('textMuted', 'surface'),
             ('link', 'background'), ('link', 'surface'),
             ('onPrimary', 'primary'), ('onPrimary', 'primaryHover'),
             ('onSelection', 'selection')]
    pairs += [(state, state + 'Surface') for state in ('success', 'warning', 'danger', 'info')]
    for foreground, background in pairs:
        ratio = contrast(colors[foreground], colors[background])
        assert ratio >= 4.5, (theme, foreground, background, ratio)
        checks.append(f'| {theme} | `{foreground}` / `{background}` | {ratio:.2f}:1 |')
    for foreground in ('focus', 'controlBorder'):
        for background in ('background', 'surface'):
            ratio = contrast(colors[foreground], colors[background])
            assert ratio >= 3, (theme, foreground, background, ratio)
            checks.append(f'| {theme} | `{foreground}` / `{background}`（非文本） | {ratio:.2f}:1 |')

parts = ['<svg xmlns="http://www.w3.org/2000/svg" width="1440" height="1480" viewBox="0 0 1440 1480">',
         '<rect width="1440" height="1480" fill="#F6FBFF"/>']


def rect(x, y, w, h, fill, radius=0):
    parts.append(f'<rect x="{x}" y="{y}" width="{w}" height="{h}" rx="{radius}" fill="{fill}"/>')


def text(x, y, label, size=16, fill='#101820', weight=400):
    parts.append(f'<text x="{x}" y="{y}" font-family="Segoe UI, Microsoft YaHei, sans-serif" font-size="{size}" font-weight="{weight}" fill="{fill}">{escape(label)}</text>')


def swatch(x, y, width, height, color, title):
    ink = '#101820' if contrast(color, '#101820') >= 4.5 else '#FFFFFF'
    if contrast(color, ink) < 4.5:
        ink = '#000000'
    rect(x, y, width, height, color, 12)
    text(x + 16, y + height - 42, title, 14, ink, 600)
    text(x + 16, y + height - 18, color, 16, ink)


text(64, 58, 'JELLYFRAME / PROJECT PALETTE', 14, '#496373', 600)
text(64, 112, '浅海蓝，让界面轻盈而清晰。', 36, weight=600)
text(64, 150, '品牌色 · 中性色 · 辅助色 · 深浅主题 · 语义状态', 17, '#496373')
text(64, 199, '01  LOGO 原色 / PRIMARY IDENTITY', 15, '#496373', 600)
for i, (key, label) in enumerate([('highlight', '浅海青 / 高光'), ('primary', '水母蓝 / 品牌主色'), ('ocean', '海洋蓝 / 渐变终点'), ('depth', '深海蓝 / 收尾')]):
    swatch(64 + i * 332, 218, 316, 126, data['logo'][key], label)
text(64, 375, '触手补色：左 #40C7DE   ·   中 #239BCF   ·   右 #188BC8', 15, '#496373')
text(64, 423, '02  品牌色阶 / BRAND SCALE', 15, '#496373', 600)
for i, (key, color) in enumerate(data['brand'].items()):
    swatch(64 + i * 120, 442, 112, 96, color, key)
text(64, 580, '03  中性色 / NEUTRALS', 15, '#496373', 600)
for i, (key, color) in enumerate(data['neutral'].items()):
    swatch(64 + i * 110, 600, 102, 94, color, key)
text(64, 737, '04  辅助色 / ACCENTS', 15, '#496373', 600)
for i, (key, label) in enumerate([('coral', '珊瑚 / 活力'), ('lime', '青柠 / 焦点'), ('mint', '薄荷 / 成功'), ('amber', '琥珀 / 警告'), ('rose', '玫瑰 / 错误')]):
    swatch(64 + i * 266, 757, 250, 96, data['accent'][key], label)
text(64, 896, '05  界面语义 / LIGHT & DARK', 15, '#496373', 600)
for index, theme in enumerate(('light', 'dark')):
    c = data['themes'][theme]
    x = 64 + index * 672
    rect(x, 916, 648, 332, c['background'], 20)
    rect(x + 16, 932, 616, 300, c['surface'], 16)
    text(x + 40, 970, '浅色主题' if theme == 'light' else '深色主题', 22, c['text'], 600)
    text(x + 40, 1004, f"正文 {c['text']}   /   次要文字 {c['textMuted']}", 16, c['textMuted'])
    rect(x + 40, 1030, 164, 44, c['primary'], 12)
    text(x + 69, 1058, '开始创作', 17, c['onPrimary'], 600)
    text(x + 232, 1058, f"操作色 {c['primary']}", 16, c['link'])
    for j, (key, label) in enumerate([('success', '成功'), ('warning', '警告'), ('danger', '错误'), ('info', '信息')]):
        sx = x + 40 + j * 146
        rect(sx, 1100, 132, 84, c[key + 'Surface'], 12)
        text(sx + 14, 1132, label, 16, c[key], 600)
        text(sx + 14, 1160, c[key], 15, c[key])
    text(x + 40, 1214, '按钮与状态文字已验证对比度 ≥ 4.5:1', 14, c['textMuted'])
text(64, 1300, '使用比例建议：中性背景 70% · 品牌蓝 20% · 辅助点缀 10%', 20, weight=600)
text(64, 1340, '亮青用于品牌和高光；浅色界面的小字号链接、白字按钮使用深海蓝 #176DB1。', 17, '#496373')
text(64, 1370, '半透明凝胶保留 native-jelly 原始材质参数；状态同时配合文字或图标表达。', 17, '#496373')
text(64, 1434, 'JellyFrame · Color System v1', 14, '#496373')
text(1096, 1434, 'HEX / CSS / JSON / SVG', 14, '#496373')
parts.append('</svg>')
(ROOT / 'palette.svg').write_text('\n'.join(parts) + '\n', encoding='utf-8')

doc = ['# JellyFrame 项目色卡', '', '> 最后更新：2026-09-08；色卡版本：1；适用版本：0.6.0-dev', '',
       '![JellyFrame 项目色卡](palette.png)', '',
       '本色卡从实际 Logo 配色扩展，沿用 `native-jelly` 的浅海蓝、珊瑚、青柠与凝胶材质。新增色阶和语义映射供后续界面使用；当前应用模板的配色不会因添加色卡自动改变。', '',
       '## Logo 的实际用色', '', '| 角色 | HEX |', '| --- | --- |']
for key, color in data['logo'].items():
    doc.append(f'| {key} | `{color}` |')
doc += ['', '伞盖渐变：`#67DDED`（0%）→ `#26B9DE`（48%）→ `#1680C7`（100%）；中间触手渐变：`#239BCF` → `#176DB1`。方向以 Logo SVG 的渐变坐标为准。', '',
        '## 基础色板', '', '| 类别 | 色号 / 色阶 |', '| --- | --- |']
for group in ('brand', 'neutral', 'accent'):
    doc.append('| ' + group + ' | ' + ' · '.join(f'{key} `{color}`' for key, color in data[group].items()) + ' |')
doc += ['', '品牌 500 是视觉主色；品牌 700 是浅色界面的主要操作色。中性色 900 和 950 分别保留原主题深底与原字标墨色。辅助色中的 mint、amber、rose 是原有半透明状态色的 RGB 基色。', '',
        '## 深浅主题语义', '', '| Token | 浅色 | 深色 |', '| --- | --- | --- |']
for key, value in data['themes']['light'].items():
    doc.append(f"| `{key}` | `{value}` | `{data['themes']['dark'][key]}` |")
doc += ['', '## 凝胶材质', '', '以下数值保留现有设计系统定义。RGBA 是叠加层参数，最终观感取决于底色，不能当成固定 HEX 或直接作为文字对比度保证。', '', '| Token | 值 |', '| --- | --- |']
doc += [f'| `{key}` | `{value}` |' for key, value in data['material'].items()]
doc += ['', '## 使用规则与接入', '',
        '- 建议中性色约 70%、品牌蓝约 20%、辅助点缀约 10%；这是视觉配比建议，不是布局约束。',
        '- 亮青优先用于标识、图形和高光。浅色主题的小字链接、白字按钮使用 `#176DB1`；不要直接在明亮的品牌 500 上叠加白色小字。',
        '- `border` 用于装饰分隔；需要识别控件边界时使用 `controlBorder`。焦点环与控件之间留出背景色间隔。',
        '- 状态同时配合文案或图标；珊瑚与青柠是点缀色，不默认绑定错误或成功。',
        '- VS Code 内部控件继续使用 `--vscode-*` 主题变量，保持用户主题与高对比主题适配；本色卡适合项目自有界面和品牌素材。',
        '- `palette.json` 是色卡数据源；运行 `python docs/assets/brand/generate_palette.py` 更新 CSS、SVG 和本文，并验证不透明颜色配对的对比度。PNG 是 SVG 的栅格预览，需在修改后重新导出。',
        '- `palette.css` 使用 `--jf-brand-*`、`--jf-neutral-*`、`--jf-accent-*`、`--jf-material-*` 和 `--jf-color-*`，避开现有 `--jf-surface` 等模板变量。导入后将语义变量映射到需要的控件样式。', '',
        '```css', '/* 引入 palette.css；默认浅色。给主题容器添加 jf-theme-dark 可切换深色。 */',
        '.app { background-color: var(--jf-color-background); color: var(--jf-color-text); }',
        '.primary-button { background-color: var(--jf-color-primary); color: var(--jf-color-on-primary); }',
        '```', '',
        'Logo 的三色渐变用于 SVG 品牌素材。嵌入式 UI 按现有渲染能力使用两色渐变 `linear-gradient(#67DDED, #1680C7)`，不将 SVG 或三色渐变支持视为运行时前提。', '',
        '## 对比度记录', '', '按 WCAG sRGB 相对亮度计算，以下不透明文字配对通过 AA 普通文本 4.5:1；标注“非文本”的焦点与控件边界配对通过 3:1。该记录只覆盖列出的组合，不代表任意叠层、渐变或整套应用均通过检查。', '',
        '| 主题 | 前景 / 背景 | 对比度 |', '| --- | --- | --- |', *checks, '']
(ROOT / 'PALETTE_zh.md').write_text('\n'.join(doc), encoding='utf-8')
print(f'Generated palette.css, palette.svg, PALETTE_zh.md; {len(checks)} contrast pairs passed.')
